<img src="{{ $message->embed(asset('img/cabecera.jpg')) }}" alt="">
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;margin-top:0in;margin-right:42.5pt;margin-bottom:.0001pt;margin-left:5.15pt;text-align:center;line-height:143%;'>LIBERACI&Oacute;N DE RESPONSABILIDAD</p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;margin-top:0in;margin-right:42.5pt;margin-bottom:.0001pt;margin-left:5.15pt;text-align:justify;line-height:143%;'>Yo, <span style="color:red;"><strong>{{ $participante->nombre }}</strong></span>, declaro que en forma voluntaria y libre he decidido participar en el evento <strong>{{ $evento->nombre }}</strong>; entiendo que participar en esta competencia es una actividad riesgosa por lo que expreso que estoy en perfectas condiciones f&iacute;sicas y de salud, as&iacute; como&nbsp;adecuadamente entrenado para participar en la misma.</p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;margin-top:11.25pt;margin-right:21.9pt;margin-bottom:.0001pt;margin-left:5.15pt;text-align:justify;line-height:143%;'>Estoy de acuerdo en cumplir con cualquier decisi&oacute;n proveniente de alg&uacute;n juez o cualquier&nbsp;autoridad del evento, en cuanto a mi capacidad para concluir con seguridad la ruta&nbsp;establecida y el cumplimiento de los tiempos establecidos para la hora de cierre de la carrera o sobre cualquier otro aspecto en relaci&oacute;n a mi participaci&oacute;n en la misma.</p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;margin-top:5.55pt;margin-right:8.55pt;margin-bottom:.0001pt;margin-left:5.15pt;text-align:justify;line-height:143%;'>Habiendo le&iacute;do esta declaraci&oacute;n, libero a los organizadores y a todos los auspiciadores, as&iacute;&nbsp;como a sus representantes y sucesores, en su conjunto las Instituciones, de reclamos o&nbsp;responsabilidad de cualquier &iacute;ndole, y/o del pago por da&ntilde;os y perjuicios que pudieran surgir&nbsp;de mi participaci&oacute;n durante o posterior al evento, aun cuando esta responsabilidad pudiera&nbsp;surgir por causas imputables a alguna de las instituciones.</p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;margin-top:5.55pt;margin-right:8.55pt;margin-bottom:.0001pt;margin-left:5.15pt;text-align:justify;line-height:143%;'>&nbsp;</p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;margin-top:5.55pt;margin-right:8.55pt;margin-bottom:.0001pt;margin-left:5.15pt;text-align:justify;line-height:143%;'>&nbsp;</p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;margin-top:.05pt;margin-right:0in;margin-bottom:.0001pt;margin-left:5.15pt;'>Firma: &nbsp;<u>&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</u></p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;'><span style="font-size:13px;">&nbsp;</span></p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;'><span style="font-size:13px;">&nbsp;</span></p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;'><span style="font-size:13px;">&nbsp;</span></p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;margin-top:11.2pt;margin-right:0in;margin-bottom:.0001pt;margin-left:5.15pt;'>C.I. o Pasaporte:&nbsp;</p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;'><span style="font-size:17px;">&nbsp;</span></p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;'><span style="font-size:17px;">&nbsp;</span></p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;margin-top:.3pt;'><span style="font-size:18px;">&nbsp;</span></p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;margin-left:5.15pt;'>Fecha: <u>&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</u></p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;'><span style="font-size:13px;">&nbsp;</span></p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;'><span style="font-size:13px;">&nbsp;</span></p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;'><span style="font-size:13px;">&nbsp;</span></p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;'><span style="font-size:13px;">&nbsp;</span></p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;'><span style="font-size:13px;">&nbsp;</span></p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;margin-top:.5pt;'><span style="font-size:19px;">&nbsp;</span></p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;margin-top:4.6pt;margin-right:0in;margin-bottom:.0001pt;margin-left:5.15pt;'>Atte.</p>
<p style='margin:0in;font-size:16px;font-family:"Arial",sans-serif;font-weight:bold;margin-top:6.05pt;margin-right:0in;margin-bottom:.0001pt;margin-left:5.15pt;'>Coordinaci&oacute;n de Inscripciones</p>
